### ISSUE TITLE
The extension fails to build on all platforms

### ISSUE THREAD

**Issue by lassoan** [SlicerIGT/aigt#15]
The extension has build error - subdirectories that are added to the build do not exist.

https://slicer.cdash.org/index.php?project=SlicerPreview&date=2021-09-13&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=aigt

I cannot figure out which modules should be included in the extension.

**Comment by Sunderlandkyl** [comment]
This commit changes the RunNeuralNet module to behave as an extension in CMake, which is the cause of the build errors: https://github.com/SlicerIGT/aigt/commit/acefcd43af414fe3772b706b82dae7f31d9ef47c

Is there a reason that RunNeuralNet needs to be an extension?

**Comment by Sunderlandkyl** [comment]
Extension is available again on all platforms: https://slicer.cdash.org/index.php?project=SlicerPreview&date=2021-09-20&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=AIGT
