### ISSUE TITLE
Unable to access dataset and trained models

### ISSUE THREAD

**Issue by miruna20** [SlicerIGT/aigt#32]
Hi,

unfortunately I am unable to access the dataset and the trained models at https://pocus.cs.queensu.ca/api/v1. Would you please let me know how I can obtain them? 

Thank you,
Miruna

**Comment by ungi** [comment]
Hi, here is another shared folder with the data: https://1drv.ms/u/s!AhiABcbe1DByhcxNwisvpLVxKOWjUg?e=a5Qwes
Please cite this paper if you use the data in your research: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7654705/

**Comment by miruna20** [comment]
Thank you very much for your answer! Would it be possible to also get the weights of the trained model?

**Comment by ungi** [comment]
Two trained models are saved in the same folder in files called SagittalSpine_04.h5 and SagittalSpine_05.h5. They are full TF models saved with weights and architecture all in one files. You can load these models with tf.keras.model.load_model(...)

**Comment by miruna20** [comment]
Thank you very much!
