### ISSUE TITLE
Resizing images in prepare_data vs. resizing using Pytorch Dataset

### ISSUE THREAD

**Issue by chriscyyeung** [SlicerIGT/aigt#36]
Seems redundant to have both. Might make more sense to resize using Pytorch transforms during training?

**Comment by ungi** [comment]
Some redundancy is not a problem, especially if we can easily skip one resizing step out of the two. Feel free to implement resize transform in the training script. If the input is already resized by the prepare_data script, then resizing will be automatically skipped during training, and training will require less time, data traffic, and storage space during training. It's a nice option to keep.
