### ISSUE TITLE
Use metics from monai and put a table of final metrics on wandb

### ISSUE THREAD

**Issue by ungi** [SlicerIGT/aigt#38]

**Comment by chriscyyeung** [comment]
I've been trying to add a table of the final metrics that updates after each run but this is not well-supported on wandb. With 
98016df, a table is logged but it gets overridden after each run. There may be a way to make it work, but simply logging the metrics (not the table) will populate the runs table without any extra work. And we can still export the results in a csv if we need to. The only downside that I can think of is that we can't show the table as a panel in the current run. @ungi what do you think?

**Comment by ungi** [comment]
I see. The current table is not ideal. I've noticed that there is tab on the left called "Runs" which creates a table view of all results. It looks like this picture below. It's actually perfect for what we needed. Besides this, saving a csv file in the outputs folder would be great for importing in Excel. If this "Runs" table is available without you explicitly adding the metrics table on the workspace, then please feel free to remove the table that is above Charts now.
![image](https://github.com/SlicerIGT/aigt/assets/2071850/22b02648-c352-43b8-9d55-6dae5b20eb6e)
