### ISSUE TITLE
Issue with Running prepare_data.py Script

### ISSUE THREAD

**Issue by pranathi-golla** [SlicerIGT/aigt#54]
I'm currently facing an issue while running the prepare_data.py script, and I could use your expertise to resolve it.

Here's a brief overview of the problem:

I exported my segmentations from 3DSlicer in the form of two files: "_segmentation.py" and "_ultrasound.py." I've placed these two files in a folder named "SegmentationOutput" and attempted to execute the following command in my terminal:

python prepare_data.py --input_dir SegmentationOutput --output_dir PatientArrays --config_file prepare_data_config.yaml --log_file "PrepareData.log"

My problem arises from the creation of the "_indices.py" file. As per my understanding of the prepare_data.py script, the "_indices.py" file should be derived from the "_segmentation.npy" file. However, the line in the script that reads seg_filename.replace("_segmentation", "_indices") seems to only change the string that describes the path to the folder, but it does not actually create the "_indices.py" file. Even if it did, just renaming "_segmentation.py" to "_indices.py" wouldn't work because the dimensions don't match. Ideally, the "_indices.py" file should have only one dimension, but it appears to be 3D when derived from "_segmentation.py."

I would greatly appreciate your assistance in understanding how to obtain the correct "_indices.py" file or any insights on how to resolve this issue.

Thank you in advance for your support.

**Comment by ungi** [comment]
Hi, if you use the latest version of the Single Slice Segmentation module in 3D Slicer, then the indices file will be created besides ultrasound and segmentation files. This was added more recently because we sometimes need to export all ultrasound frames from Slicer, not just the ones manually segmented. Indices just contains the list of frame numbers which have a segmentation.

**Comment by pranathi-golla** [comment]
Thank you very much for your response.

**Comment by pranathi-golla** [comment]
The latest version of the Single Slice Segmentation module has addressed the issue of exporting the _indices.py file. However, I am currently experiencing an error while manually segmenting (that I didn't encounter with the older module version). The error message I'm encountering reads as follows: 

File ".........../aigt/SlicerExtension/LiveUltrasoundAi/SingleSliceSegmentation/SingleSliceSegmentation.py", line 302, in onCaptureButton
activeBrowserNode = slicer.modules.sequences.toolBar().activeBrowserNode()
AttributeError: qMRMLSequenceBrowserToolBar has no attribute named 'activeBrowserNode'

I kindly request your assistance in understanding the cause of this error and finding a solution for it. Thank you.

**Comment by ungi** [comment]
That error message shows that you don't have a sequence browser selected. Could you visualize the sequences toolbar (View/Toolbars/Sequence browser) and make sure your input sequence browser (that holds the recorded ultrasound scan) is selected in the toolbar?

It should be auto-selected if you select the same browser in the Single Slice Segmentation module as input. But it may only take effect when you enter the module after loading a saved scene.
